### ISSUE TITLE
WebSocketException

### ISSUE THREAD

**Issue by MartinStokelj** [ErnestoGarciaGenesys/bayeux-client-dotnet#4]
Hello,
i am trying to connect 
Uri = new Uri("wss://" + _ip + "/bayeux/websocket"),
And getting error
System.Net.WebSockets.WebSocketException: 'Unable to connect to the remote server'

WebException: The request was aborted: Could not create SSL/TLS secure channel.

Uri over html and javascript works ok, so i dont understand why there is error.
I am also wondering if its possible to add certificate to this secure connection?

**Comment by ErnestoGarciaGenesys** [comment]
Hi, regarding the exception on connecting, if you are not getting enough info from the exception contents, you may want to enable .NET network logging, described [here](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/how-to-configure-network-tracing).

Regarding setting a certificate, I am not sure how to do that. You may want to look into the .NET docs for this. WebSocketTransportOptions accepts a factory method for creating WebSockets; you could provide your custom factory method if that flexibility is needed.

**Comment by MartinStokelj** [comment]
The problem was certificate i found solution to add it in.


	public async Task Open(CancellationToken cancellationToken)
	{
		if (receiverLoopCancel != null)
		{
			receiverLoopCancel.Cancel();
			await receiverLoopTask;
		}

		if (webSocket != null)
			webSocket.Dispose();

		ServicePointManager.Expect100Continue = true;
		ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls;
		webSocket = webSocketFactory();
		if (webSocket is ClientWebSocket)
		{
			(webSocket as ClientWebSocket).Options.ClientCertificates = new X509CertificateCollection();
			(webSocket as ClientWebSocket).Options.ClientCertificates.Add(BayeuxClient.twCertificate);
		}
		try
		{
			await webSocket.ConnectAsync(uri, cancellationToken);
		}
		catch (Exception e)
		{
			throw new BayeuxTransportException("WebSocket connect failed.", e, transportClosed: true);
		}

		receiverLoopCancel = new CancellationTokenSource();
		receiverLoopTask = StartReceiverLoop(receiverLoopCancel.Token);
	}

**Comment by ErnestoGarciaGenesys** [comment]
I see that you need to set some ClientWebSocket properties in order to set the client certificate.

I would recommend to set a custom factory method in WebSocketTransportOptions.WebSocketFactory, instead of modifying library code.
